FROM childcareregistry.azurecr.io/pybaseimage:latest

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt 

COPY . .
RUN python manage.py makemigrations
RUN python manage.py migrate --run-syncdb

EXPOSE 8000 8080

CMD [ "python", "manage.py", "runserver" , "0.0.0.0:8080"]
